# Enable forge global version checking
versionCheck = true
# does the splashscreen run
splashscreen = true
defaultConfigPath = "defaultconfigs"
# max threads for parallel loading : -1 uses Runtime#availableProcessors
maxThreads = -1
shownMods = ["minecraft", "smoothboot", "forge", "entity_culling", "packrewards", "ferritecore", "placebo", "pixelmon", "tcg", "clientresetpacket", "serverredirect", "jei"]